name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Build
      run: |
           ls -la
           go build -v

    - name: Test
      run: go test -v
      
    - name: Check
      run: |
          ls -la
          pwd
          ./GoBuildRepo


  #  - name: Go Publishr
  # You may pin to the exact commit or the version.
  # uses: PackagrIO/action-publishr-go@5500e68ee3673e8e8f9b825b72c67198d97804f3
  #    uses: PackagrIO/action-publishr-go@master
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #    with:
    # Assets to upload
  #      upload_assets: 'HelloWorld' # optional
