name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Go Publishr
  # You may pin to the exact commit or the version.
  # uses: PackagrIO/action-publishr-go@5500e68ee3673e8e8f9b825b72c67198d97804f3
      uses: PackagrIO/action-publishr-go@v1.0.1
      with:
    # Commit Author
        author_name: MateoTomasBilbao # default is packagrio-bot
    # Commit Author Email
        author_email: mateo.bilbao@endava.com # default is packagr-io[bot]@users.noreply.github.com
    # Assets to upload
        # upload_assets: # optional
    # Working Directory
        cwd: './GoBuildRepo/'# optional, default is 
